# SPDX-FileCopyrightText: 2018-2024 Jimmi Holst Christensen
# SPDX-FileCopyrightText: 2024 Caleb Depatie 
#
# SPDX-License-Identifier: MIT

name: Checks
on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: dx-oss/nix-shell-action@v11
        with:
          script: |
            zig build test
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check bench.zig
